### ISSUE TITLE
Bug on editing created items if checked 

### ISSUE THREAD

**Issue by MicroLink26** [mdn/todo-vue#1]
**Reproduce the bug** 
Create an item
Check this item
Edit this item
Cancel edition

The item is no more checked

**How to resolve (fast and easy)** 
On toDoItem.vue switch isDone from data to computed to preserve reactivity

**Comment by chrisdavidmills** [comment]
I've confirmed the bug; thanks for reporting, @MicroLink26 !

Are you interested in submitting a PR for this change?

**Comment by chrisdavidmills** [comment]
Fixed by https://github.com/mdn/todo-vue/pull/2.

Thanks again @MicroLink26

**Comment by chrisdavidmills** [comment]
I've also added a section to the tutorial to cover this:

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_conditional_rendering#Fixing_a_small_bug_with_isDone_status

What do you think? I'm actually surprise that the reactivity is not preserved by just including it inside `data() {}`, but then again I'm fairly new to Vue.

**Comment by MicroLink26** [comment]
Inside data, isDone is set up with this.done only on component load, it's
only initialization.
That's why we need to use computed property.

There are two other baddest ways to preserve data (no tested, they're bad):
using v-model="isDone" on checkbox instead of :checked="isDone"
using v-show instead of v-if (DOM is preserved)

Le ven. 29 mai 2020 à 12:14, Chris Mills <notifications@github.com> a
écrit :

**Comment by chrisdavidmills** [comment]
Cool, thank you for the further explanation.
