### ISSUE TITLE
Vue todolist app has some bug

### ISSUE THREAD

**Issue by meredithyan** [mdn/todo-vue#133]
guys:

I followed the [instructions](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_refs_focus_management) to create a vue to-do-list app, but I think there is a bug.

that is: when we click the save button from ToDoItemEditForm component, we can’t get back to the ToDoItem view , let alone the focus management ( we want move the focus to the input in the ToDoItem view)

at first, I think that is my problem, then I checked your [live version](https://mdn.github.io/todo-vue/), then I find the same problem.

https://github.com/mdn/todo-vue/assets/495429/da12569a-7f4a-4b2c-86e9-39d60ea12cf4

**Comment by caugner** [comment]
Reproduced the issue with the [live version](https://mdn.github.io/todo-vue/):

1. Click "Edit" on any item,
2. Click "Save" without changing the title,
3. Nothing happens, but the effect should be the same as clicking the "Cancel" button.

**Comment by OnyileFelix1** [comment]
do you guys need help in the documentation
