### ISSUE TITLE
“Getting started with Vue” doc: Behaviour change when there is no visible content inside <template>

### ISSUE THREAD

**Issue by gluttony38** [mdn/todo-vue#64]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_getting_started

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_getting_started#making_a_couple_of_changes

### What information was incorrect, unhelpful, or incomplete?

Hi,

When removing HelloWorld from App.vue template, template became empty, documentation say we have one error because of not using registered component, this is OK but there is also an error because template is empty:
```
moz-todo-vue\src\App.vue
   1:1  error  The template requires child element                          vue/valid-template-root
  10:5  error  The "HelloWorld" component has been registered but not used  vue/no-unused-components

✖ 2 problems (2 errors, 0 warnings)
```
Also (edit: this one is already reported in mdn/todo-vue#65), after removing HelloWorld import and component, it is said:
"Your rendered app **should no longer show an error, just a blank page**, as we currently have no visible content inside <template>."
But there is actually still:
```
moz-todo-vue\src\App.vue
  1:1  error  The template requires child element  vue/valid-template-root

✖ 1 problem (1 error, 0 warnings)
```

Edit: also, in https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_getting_started#initializing_a_new_project, on `vue create moz-todo-vue` there is a step that is not mentioned where we have to choose between Vue2 and Vue3, I choose Vue3.

Edit2: in another page (https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_methods_events_models#creating_a_new_to-do_form) there is a typo:
```
import ToDoForm from './components/ToDoForm';
```
instead of
```
import ToDoForm from './components/ToDoForm.vue';
```

Thanks.

### What did you expect to see?

Proper text about empty template error message.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn/tools_and_testing/client-side_javascript_frameworks/vue_getting_started`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_getting_started
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/vue_getting_started/index.md
* Last commit: https://github.com/mdn/content/commit/73ea2b0f8ebfab23630b86e64b14a7b1f7577679
* Document last modified: 2022-05-13T04:41:50.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot for opening the issue @gluttony38. The docs are now updated to show the error in https://github.com/mdn/content/pull/23696

I'm going to close this one as done now. Thank you :)
